workflows:
  version: 2
  multiple-java-versions:
    jobs:
      - checkout_code
      - update_dependencies:
          requires:
            - checkout_code
      - java-8:
          requires:
            - update_dependencies
      - java-11:
          requires:
            - checkout_code

version: 2

job_defaults: &job_defaults
  working_directory: /src

  docker:
    - image: openjdk:8-jdk

mvn_job_defaults: &mvn_job_defaults
  <<: *job_defaults

  steps:
    - restore_cache:
        key: code-repo-{{ .Environment.CIRCLE_SHA1 }}-{{ .Environment.CIRCLE_TAG }}

    - run:
        name: Prep for Maven cache load
        command: |
          cat $(find app -name pom.xml ! -path */src/* | sort) > /tmp/all-poms

    - restore_cache:
        keys:
          - dependencies-{{ checksum "/tmp/all-poms" }}

    - run:
        name: Run Maven build
        command: ./mvnw -B -U clean install

    - run:
        name: Save test results
        command: |
          mkdir -p ~/junit/
          find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
        when: always

    - store_test_results:
        path: ~/junit

    - store_artifacts:
        path: ~/junit

jobs:
  checkout_code:
    <<: *job_defaults

    steps:
      - checkout

      - save_cache:
          key: code-repo-{{ .Environment.CIRCLE_SHA1 }}-{{ .Environment.CIRCLE_TAG }}
          paths:
            - /src

  update_dependencies:
    <<: *job_defaults

    steps:
      - restore_cache:
          keys:
            - code-repo-{{ .Environment.CIRCLE_SHA1 }}-{{ .Environment.CIRCLE_TAG }}

      - run:
          name: Prep for Maven cache load
          command: |
            cat $(find app -name pom.xml ! -path */src/* | sort) > /tmp/all-poms

      - restore_cache:
          keys:
            - dependencies-{{ checksum "/tmp/all-poms" }}

      - run:
          name: Update dependencies
          command: |
            ./mvnw -B -U -DskipTests package dependency:go-offline

      - save_cache:
          key: dependencies-{{ checksum "/tmp/all-poms" }}
          paths:
            - /root/.m2


  java-8:
    <<: *mvn_job_defaults

  java-11:
    <<: *mvn_job_defaults

    docker:
      - image: openjdk:11-jdk

